### PR TITLE
Fix ConcatSource.updateHash to work with strings

### PR DESCRIPTION
**Pull request by gnarf**
not sure if this matters at all to anyone anymore, but I found myself looking at a stack trace here today, so here's the fix.

### CODE REVIEW

**Comment by gaearon** [comment]
I’m not a maintainer but I think this is a bit hard to review because of unrelated whitespace changes.

**Comment by gnarf** [comment]
https://github.com/webpack/core/pull/27/files?w=1 -- I just fixed the tabbing

**Comment by gaearon** [comment]
Could you clarify what the behavior is before and after this change?
I’m not a maintainer but I’m interested in improvements to this module as it affects us downstream.

**Comment by gaearon** [comment]
(As for whitespace, I think the decision to use tabs is intentional given that all of WP codebase does it. I’m not a huge fan but it would probably make sense to preserve existing style.)

**Comment by SpaceK33z** [comment]
Can confirm, tabs everywhere!

**Comment by gnarf** [comment]
@gaearon before this change, if you have a `ConcatSource` that has a plain `String` in it, you can't use `.updateHash` on it, because the code for `updateHash` didn't check for `String`s and it will try to call `String.updateHash(hash)` instead of `hash.update(String)`

https://github.com/webpack/core/pull/27/files?w=1 is an easy way to see a diff without whitespace.

This code isn't used in webpack 2, I already landed the same change in the `webpack-sources` module, so this is just a shim for the webpack 1 branch.  There is a test case included in the other linked PR: https://github.com/webpack/webpack-sources/issues/1

**Comment by gnarf** [comment]
WRT to the tabs problem, y'all really should add a `.editorconfig` to this repo :)

My editor replaced those without me knowing because my default editorconfig settings are for 2spaces

**Comment by gaearon** [comment]
Thanks for explaining!

**Comment by gnarf** [comment]
I sent in a PR for a `.editorconfig` file to help stop future me's from having our whitespace settings auto-destroy all the tabs :)

**Comment by gnarf** [comment]
@SpaceK33z can we get this one landed too? the `webpack-sources` version already has this change (and the test case for it)

**Comment by SpaceK33z** [comment]
@gnarf, I'm not really maintaining this repo (except for closing / merging some simple things), so it's probably for the best if @sokra checks & merges this.

**Comment by sokra** [comment]
Thanks

**Pull request merged**
